version: '3'
services:
  app:
    container_name: tour
    build: .
    working_dir: /code
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/code
    tty: true
    depends_on:
      - db
  db:
    container_name: tour-db
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - 5432:5432
